### ISSUE TITLE
Google test as a submodule

### ISSUE THREAD

**Issue by Kristian-Popov** [PhDP/cmake-gtest-gbench-starter#1]
Good evening,
Thank you for a great project. I have one comment though - Google benchmark is added as a submodule, but Google test is just copied, it would be great to be a submodule, it's easier to update them this way.
Also I like when all third-party external modules and libraries are put in one folder (contrib or something like that) , but current solution is also ok.

Best regards,
Krystian Popov

**Comment by PhDP** [comment]
Hi Kristian! That's a good point, I remember having issues with Google Test as a submodule but I'll try to fix it ASAP. Thanks for the feedback!
